// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: hostinfo.proto

package hostinfo_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip    string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port  int32  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	OS    string `protobuf:"bytes,4,opt,name=OS,proto3" json:"OS,omitempty"`
	Label string `protobuf:"bytes,5,opt,name=Label,proto3" json:"Label,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Host) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Host) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *Host) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	AuthMode int32  `protobuf:"varint,2,opt,name=AuthMode,proto3" json:"AuthMode,omitempty"`
	Auth     string `protobuf:"bytes,3,opt,name=Auth,proto3" json:"Auth,omitempty"`
	ID       string `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{1}
}

func (x *Authentication) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Authentication) GetAuthMode() int32 {
	if x != nil {
		return x.AuthMode
	}
	return 0
}

func (x *Authentication) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *Authentication) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type HostAndAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip       string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port     int32  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	OS       string `protobuf:"bytes,4,opt,name=OS,proto3" json:"OS,omitempty"`
	Label    string `protobuf:"bytes,5,opt,name=Label,proto3" json:"Label,omitempty"`
	Username string `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	AuthMode int32  `protobuf:"varint,7,opt,name=AuthMode,proto3" json:"AuthMode,omitempty"`
	Auth     string `protobuf:"bytes,8,opt,name=Auth,proto3" json:"Auth,omitempty"`
}

func (x *HostAndAuthentication) Reset() {
	*x = HostAndAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostAndAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAndAuthentication) ProtoMessage() {}

func (x *HostAndAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAndAuthentication.ProtoReflect.Descriptor instead.
func (*HostAndAuthentication) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{2}
}

func (x *HostAndAuthentication) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostAndAuthentication) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostAndAuthentication) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostAndAuthentication) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *HostAndAuthentication) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *HostAndAuthentication) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HostAndAuthentication) GetAuthMode() int32 {
	if x != nil {
		return x.AuthMode
	}
	return 0
}

func (x *HostAndAuthentication) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type HostInfoIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HostInfoIdRequest) Reset() {
	*x = HostInfoIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIdRequest) ProtoMessage() {}

func (x *HostInfoIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIdRequest.ProtoReflect.Descriptor instead.
func (*HostInfoIdRequest) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{3}
}

func (x *HostInfoIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HostInfoIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *HostInfoIdsRequest) Reset() {
	*x = HostInfoIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIdsRequest) ProtoMessage() {}

func (x *HostInfoIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIdsRequest.ProtoReflect.Descriptor instead.
func (*HostInfoIdsRequest) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{4}
}

func (x *HostInfoIdsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type HostInfoIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *HostInfoIpRequest) Reset() {
	*x = HostInfoIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIpRequest) ProtoMessage() {}

func (x *HostInfoIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIpRequest.ProtoReflect.Descriptor instead.
func (*HostInfoIpRequest) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{5}
}

func (x *HostInfoIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type HostInfoIsExists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
}

func (x *HostInfoIsExists) Reset() {
	*x = HostInfoIsExists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIsExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIsExists) ProtoMessage() {}

func (x *HostInfoIsExists) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIsExists.ProtoReflect.Descriptor instead.
func (*HostInfoIsExists) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{6}
}

func (x *HostInfoIsExists) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type HostInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*Host `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *HostInfoResp) Reset() {
	*x = HostInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoResp) ProtoMessage() {}

func (x *HostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoResp.ProtoReflect.Descriptor instead.
func (*HostInfoResp) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{7}
}

func (x *HostInfoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *HostInfoResp) GetData() []*Host {
	if x != nil {
		return x.Data
	}
	return nil
}

type HostInfoPageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size  int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *HostInfoPageInfo) Reset() {
	*x = HostInfoPageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoPageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoPageInfo) ProtoMessage() {}

func (x *HostInfoPageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoPageInfo.ProtoReflect.Descriptor instead.
func (*HostInfoPageInfo) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{8}
}

func (x *HostInfoPageInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *HostInfoPageInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_hostinfo_proto protoreflect.FileDescriptor

var file_hostinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x53, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x22,
	0x6c, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x75, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0xbd, 0x01,
	0x0a, 0x15, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x4f,
	0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x75, 0x74,
	0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x75, 0x74, 0x68, 0x22, 0x23, 0x0a,
	0x11, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x26, 0x0a, 0x12, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x48, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x2c, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x73, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0x3f, 0x0a,
	0x0c, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c,
	0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0xff, 0x02, 0x0a,
	0x08, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x08, 0x46, 0x69, 0x6e,
	0x64, 0x50, 0x61, 0x67, 0x65, 0x12, 0x11, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x35, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x05, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x0b, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x49, 0x70, 0x12, 0x12, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x48, 0x6f, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x07,
	0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x3b, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hostinfo_proto_rawDescOnce sync.Once
	file_hostinfo_proto_rawDescData = file_hostinfo_proto_rawDesc
)

func file_hostinfo_proto_rawDescGZIP() []byte {
	file_hostinfo_proto_rawDescOnce.Do(func() {
		file_hostinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_hostinfo_proto_rawDescData)
	})
	return file_hostinfo_proto_rawDescData
}

var file_hostinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_hostinfo_proto_goTypes = []interface{}{
	(*Host)(nil),                  // 0: Host
	(*Authentication)(nil),        // 1: Authentication
	(*HostAndAuthentication)(nil), // 2: HostAndAuthentication
	(*HostInfoIdRequest)(nil),     // 3: HostInfoIdRequest
	(*HostInfoIdsRequest)(nil),    // 4: HostInfoIdsRequest
	(*HostInfoIpRequest)(nil),     // 5: HostInfoIpRequest
	(*HostInfoIsExists)(nil),      // 6: HostInfoIsExists
	(*HostInfoResp)(nil),          // 7: HostInfoResp
	(*HostInfoPageInfo)(nil),      // 8: HostInfoPageInfo
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_hostinfo_proto_depIdxs = []int32{
	0, // 0: HostInfoResp.data:type_name -> Host
	8, // 1: HostInfo.FindPage:input_type -> HostInfoPageInfo
	2, // 2: HostInfo.Create:input_type -> HostAndAuthentication
	4, // 3: HostInfo.Delete:input_type -> HostInfoIdsRequest
	0, // 4: HostInfo.UpdateHost:input_type -> Host
	1, // 5: HostInfo.UpdateAuthentication:input_type -> Authentication
	5, // 6: HostInfo.IsExistByIp:input_type -> HostInfoIpRequest
	9, // 7: HostInfo.FindAll:input_type -> google.protobuf.Empty
	7, // 8: HostInfo.FindPage:output_type -> HostInfoResp
	9, // 9: HostInfo.Create:output_type -> google.protobuf.Empty
	9, // 10: HostInfo.Delete:output_type -> google.protobuf.Empty
	9, // 11: HostInfo.UpdateHost:output_type -> google.protobuf.Empty
	9, // 12: HostInfo.UpdateAuthentication:output_type -> google.protobuf.Empty
	6, // 13: HostInfo.IsExistByIp:output_type -> HostInfoIsExists
	7, // 14: HostInfo.FindAll:output_type -> HostInfoResp
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hostinfo_proto_init() }
func file_hostinfo_proto_init() {
	if File_hostinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hostinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostAndAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIsExists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoPageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hostinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostinfo_proto_goTypes,
		DependencyIndexes: file_hostinfo_proto_depIdxs,
		MessageInfos:      file_hostinfo_proto_msgTypes,
	}.Build()
	File_hostinfo_proto = out.File
	file_hostinfo_proto_rawDesc = nil
	file_hostinfo_proto_goTypes = nil
	file_hostinfo_proto_depIdxs = nil
}
