// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: hostinfo.proto

package hostinfo_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip    string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port  int32             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Os    string            `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Label map[string]string `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Host) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Host) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Host) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Host) GetLabel() map[string]string {
	if x != nil {
		return x.Label
	}
	return nil
}

type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AuthMode int32  `protobuf:"varint,2,opt,name=authMode,proto3" json:"authMode,omitempty"`
	Auth     string `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Id       int32  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{1}
}

func (x *Authentication) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Authentication) GetAuthMode() int32 {
	if x != nil {
		return x.AuthMode
	}
	return 0
}

func (x *Authentication) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *Authentication) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HostAndAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip       string            `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port     int32             `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Os       string            `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Label    map[string]string `protobuf:"bytes,5,rep,name=label,proto3" json:"label,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Username string            `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	AuthMode int32             `protobuf:"varint,7,opt,name=authMode,proto3" json:"authMode,omitempty"`
	Auth     string            `protobuf:"bytes,8,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *HostAndAuthentication) Reset() {
	*x = HostAndAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostAndAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAndAuthentication) ProtoMessage() {}

func (x *HostAndAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAndAuthentication.ProtoReflect.Descriptor instead.
func (*HostAndAuthentication) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{2}
}

func (x *HostAndAuthentication) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HostAndAuthentication) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostAndAuthentication) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostAndAuthentication) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostAndAuthentication) GetLabel() map[string]string {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *HostAndAuthentication) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HostAndAuthentication) GetAuthMode() int32 {
	if x != nil {
		return x.AuthMode
	}
	return 0
}

func (x *HostAndAuthentication) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

//	message HostInfoIdRequest{
//	 int32 id = 1;
//	}
type HostInfoIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *HostInfoIdsRequest) Reset() {
	*x = HostInfoIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIdsRequest) ProtoMessage() {}

func (x *HostInfoIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIdsRequest.ProtoReflect.Descriptor instead.
func (*HostInfoIdsRequest) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{3}
}

func (x *HostInfoIdsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type HostInfoIpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *HostInfoIpRequest) Reset() {
	*x = HostInfoIpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIpRequest) ProtoMessage() {}

func (x *HostInfoIpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIpRequest.ProtoReflect.Descriptor instead.
func (*HostInfoIpRequest) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{4}
}

func (x *HostInfoIpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type HostInfoIsExists struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
}

func (x *HostInfoIsExists) Reset() {
	*x = HostInfoIsExists{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoIsExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoIsExists) ProtoMessage() {}

func (x *HostInfoIsExists) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoIsExists.ProtoReflect.Descriptor instead.
func (*HostInfoIsExists) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{5}
}

func (x *HostInfoIsExists) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type HostInfoPageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size  int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *HostInfoPageInfo) Reset() {
	*x = HostInfoPageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoPageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoPageInfo) ProtoMessage() {}

func (x *HostInfoPageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoPageInfo.ProtoReflect.Descriptor instead.
func (*HostInfoPageInfo) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{6}
}

func (x *HostInfoPageInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *HostInfoPageInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type HostInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*Host `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Error string  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Code  int32   `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *HostInfoResp) Reset() {
	*x = HostInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoResp) ProtoMessage() {}

func (x *HostInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoResp.ProtoReflect.Descriptor instead.
func (*HostInfoResp) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{7}
}

func (x *HostInfoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *HostInfoResp) GetData() []*Host {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HostInfoResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HostInfoResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type HostInfoDefResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Code  int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *HostInfoDefResp) Reset() {
	*x = HostInfoDefResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hostinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfoDefResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfoDefResp) ProtoMessage() {}

func (x *HostInfoDefResp) ProtoReflect() protoreflect.Message {
	mi := &file_hostinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfoDefResp.ProtoReflect.Descriptor instead.
func (*HostInfoDefResp) Descriptor() ([]byte, []int) {
	return file_hostinfo_proto_rawDescGZIP(), []int{8}
}

func (x *HostInfoDefResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HostInfoDefResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_hostinfo_proto protoreflect.FileDescriptor

var file_hostinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01,
	0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x48, 0x6f, 0x73, 0x74,
	0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x1a, 0x38, 0x0a, 0x0a, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6c, 0x0a, 0x0e,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x75,
	0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x9a, 0x02, 0x0a, 0x15, 0x48,
	0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x37, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x6e,
	0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x61, 0x75, 0x74, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74,
	0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x38, 0x0a,
	0x0a, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x26, 0x0a, 0x12, 0x48, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0x23, 0x0a, 0x11, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x22, 0x3c, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x69, 0x0a, 0x0c, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3b, 0x0a, 0x0f, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xed, 0x02, 0x0a, 0x08, 0x48, 0x6f, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x11, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x44, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x13, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x44, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x05, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x39, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x07, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0c,
	0x46, 0x69, 0x6e, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x42, 0x79, 0x49, 0x70, 0x12, 0x12, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x41, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x3b, 0x68, 0x6f,
	0x73, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_hostinfo_proto_rawDescOnce sync.Once
	file_hostinfo_proto_rawDescData = file_hostinfo_proto_rawDesc
)

func file_hostinfo_proto_rawDescGZIP() []byte {
	file_hostinfo_proto_rawDescOnce.Do(func() {
		file_hostinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_hostinfo_proto_rawDescData)
	})
	return file_hostinfo_proto_rawDescData
}

var file_hostinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hostinfo_proto_goTypes = []interface{}{
	(*Host)(nil),                  // 0: Host
	(*Authentication)(nil),        // 1: Authentication
	(*HostAndAuthentication)(nil), // 2: HostAndAuthentication
	(*HostInfoIdsRequest)(nil),    // 3: HostInfoIdsRequest
	(*HostInfoIpRequest)(nil),     // 4: HostInfoIpRequest
	(*HostInfoIsExists)(nil),      // 5: HostInfoIsExists
	(*HostInfoPageInfo)(nil),      // 6: HostInfoPageInfo
	(*HostInfoResp)(nil),          // 7: HostInfoResp
	(*HostInfoDefResp)(nil),       // 8: HostInfoDefResp
	nil,                           // 9: Host.LabelEntry
	nil,                           // 10: HostAndAuthentication.LabelEntry
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_hostinfo_proto_depIdxs = []int32{
	9,  // 0: Host.label:type_name -> Host.LabelEntry
	10, // 1: HostAndAuthentication.label:type_name -> HostAndAuthentication.LabelEntry
	0,  // 2: HostInfoResp.data:type_name -> Host
	6,  // 3: HostInfo.FindPage:input_type -> HostInfoPageInfo
	2,  // 4: HostInfo.Create:input_type -> HostAndAuthentication
	3,  // 5: HostInfo.Delete:input_type -> HostInfoIdsRequest
	0,  // 6: HostInfo.UpdateHost:input_type -> Host
	1,  // 7: HostInfo.UpdateAuthentication:input_type -> Authentication
	11, // 8: HostInfo.FindAll:input_type -> google.protobuf.Empty
	4,  // 9: HostInfo.FindHostByIp:input_type -> HostInfoIpRequest
	7,  // 10: HostInfo.FindPage:output_type -> HostInfoResp
	8,  // 11: HostInfo.Create:output_type -> HostInfoDefResp
	8,  // 12: HostInfo.Delete:output_type -> HostInfoDefResp
	8,  // 13: HostInfo.UpdateHost:output_type -> HostInfoDefResp
	8,  // 14: HostInfo.UpdateAuthentication:output_type -> HostInfoDefResp
	7,  // 15: HostInfo.FindAll:output_type -> HostInfoResp
	2,  // 16: HostInfo.FindHostByIp:output_type -> HostAndAuthentication
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_hostinfo_proto_init() }
func file_hostinfo_proto_init() {
	if File_hostinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hostinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostAndAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoIsExists); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoPageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hostinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostInfoDefResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hostinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hostinfo_proto_goTypes,
		DependencyIndexes: file_hostinfo_proto_depIdxs,
		MessageInfos:      file_hostinfo_proto_msgTypes,
	}.Build()
	File_hostinfo_proto = out.File
	file_hostinfo_proto_rawDesc = nil
	file_hostinfo_proto_goTypes = nil
	file_hostinfo_proto_depIdxs = nil
}
